/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
