/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.spencerduberry.hotelreservation.utils;

public class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
